name: kids_playroom
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# --------->>>>  Flutter version 3.16.5  <<<<<----------------
# --------->>>>  Dart version 3.2.3  <<<<<----------------
# --------->>>> Code Structure :- GetX <<<<<----------------


version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  sizer: ^2.0.15
  get_storage: ^2.1.1
  fluttertoast: ^8.2.4
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  sqflite: ^2.3.0
  flutter_tts: ^3.8.5
  animate_do: ^3.1.2
  rate_my_app: ^2.0.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  floodfill_image: ^0.0.8
  flutter_colorpicker: ^1.0.3
  gallery_saver: ^2.3.2
  collection: 1.18.0
  google_mobile_ads: ^4.0.0
  dio: ^5.4.0
  photo_view: ^0.14.0
  youtube_player_flutter: ^8.1.2
  in_app_purchase: ^3.1.12
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/database/
    - assets/icons/
    - assets/background/
    - assets/category/
    - assets/subcategory/
    - assets/subcategory/home_fruits.png
    - assets/item/
    - assets/drag assets/alphabets/
    - assets/drag assets/alphabets_objects/
    - assets/drag assets/animals/
    - assets/drag assets/animation/
#    - assets/drag assets/background/
    - assets/drag assets/birds/
    - assets/drag assets/category/
    - assets/drag assets/colours/
    - assets/drag assets/counting/
    - assets/drag assets/database/
    - assets/drag assets/days/
    - assets/drag assets/education/
    - assets/drag assets/fruits/
    - assets/drag assets/icons/
    - assets/drag assets/images/
    - assets/drag assets/lower/
    - assets/drag assets/money/
    - assets/drag assets/months/
    - assets/drag assets/numbers/
    - assets/drag assets/shapes/
    - assets/drag assets/time/
    - assets/drag assets/upper/
    - assets/drag assets/vehicles/
    - assets/sounds/

  fonts:
    - family: Angella
      fonts:
        - asset: fonts/angella/Angella_demo.otf
    - family: Urbanist
      fonts:
        - asset: fonts/urbanist/Urbanist-Regular.ttf
    - family: UrbanistBlack
      fonts:
        - asset: fonts/urbanist/Urbanist-Black.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
